<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.teknek.org.apache.livy</groupId>
    <artifactId>livy-main</artifactId>
    <version>0.9.0-edgyrc1</version>
  </parent>
  <groupId>io.teknek.org.apache.livy</groupId>
  <artifactId>livy-client-common</artifactId>
  <version>0.9.0-edgyrc1</version>
  <name>livy-client-common</name>
  <dependencies>
    <dependency>
      <groupId>io.teknek.org.apache.livy</groupId>
      <artifactId>livy-api</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.esotericsoftware</groupId>
      <artifactId>kryo-shaded</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-reload4j</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
